format = """
$time$username[@](blue)$hostname$directory$git_branch$git_status$git_state$cmd_duration
$character"""

add_newline = false
command_timeout = 800

[time]
format = "[\\[$time\\]]($style) "
style = "dimmed purple"
disabled = false

[username]
format = "[$user]($style)"
style_user = "blue"
style_root = "bold red"
show_always = true
disabled = false

[hostname]
format = "[$hostname]($style) "
style = "blue"
ssh_only = false
disabled = false

[directory]
format = "[$path]($style) [$read_only]($read_only_style)"
style = "cyan"
truncate_to_repo = false
truncation_symbol = ""
truncation_length = 4
fish_style_pwd_dir_length = 1
read_only = " "
read_only_style = "cyan"
disabled = false

[git_branch]
format = "[\\($branch\\)]($style) "
disabled = false

[git_status]
format = "([$ahead_behind]($style) )"
style = "yellow"
diverged = "⇡⇣"
disabled = false

[git_state]
disabled = false

[character]
format = "$symbol "
success_symbol = "[](bold white)"
error_symbol = "[](bold white)"
disabled = false

[cmd_duration]
min_time = 0
format = "[$duration]($style)"
style = "red"
disabled = false
