#!/bin/sh

backlight_path="/sys/class/backlight/intel_backlight/"
max_brightness=$(cat $backlight_path/max_brightness)

label() {
    echo "ﯧ"
}

value() {
    current_brightness=$(cat $backlight_path/brightness)
    scaled_brightness=$(awk -v x=$current_brightness -v y=$max_brightness 'BEGIN { printf "%i", (x/y*100)}')

    echo $scaled_brightness
}

if [[ $1 == "label" ]]; then
   label
elif [[ $1 == "value" ]]; then
   value
fi
