#!/bin/sh

network_name=$(nmcli connection show --active | tr -d '\n' | awk '{print $5}')

label() {
    if [[ -z $network_name ]]; then
        label=""
    else

        label=""
    fi

    echo $label
}

value() {
    if [[ -z $network_name ]]; then
        echo "No Internet"
    else
        echo $network_name
    fi
}

if [[ $1 == "label" ]]; then
   label
elif [[ $1 == "value" ]]; then
   value
fi
