#!/bin/sh

volume=$(pulseaudio-ctl full-status | awk '{print $1}')
muted=$(pulseaudio-ctl full-status | awk '{print $2}')

label() {
    if [[ $muted == "yes" ]]; then
        label="ﱝ"
    else 
        if [[ $volume -gt "60" ]]; then
            label="墳"
        elif [[ $volume -gt "30" ]]; then
            label="奔"
        else
            label="奄"
        fi
    fi

    echo $label
}

value() {
    echo $volume
}

if [[ $1 == "label" ]]; then
   label
elif [[ $1 == "value" ]]; then
   value
fi
