#!/bin/sh

volume=$(amixer sget Master | awk '/Left:/ { print $5 }' | sed -e "s/[][%]//g")
muted=$(amixer sget Master | awk '/Left:/ { print $6 }' | sed -e "s/[][%]//g")

label() {
    if [[ $muted == "off" ]]; then
        label="󰝟"
    else
        if [[ $volume -gt "60" ]]; then
            label="󰕾"
        elif [[ $volume -gt "30" ]]; then
            label="󰖀"
        else
            label="󰕿"
        fi
    fi

    echo $label
}

value() {
    echo $volume
}

if [[ $1 == "label" ]]; then
   label
elif [[ $1 == "value" ]]; then
   value
fi
