format = """$time$cmd_duration$username$hostname $directory$git_branch$git_status$git_state\n$character"""

add_newline = false
command_timeout = 800

[username]
format = "[$user]($style)"
style_user = "bold cyan"
show_always = true
disabled = false

[hostname]
format = "[@$hostname]($style)"
style = "bold cyan"
ssh_only = false
disabled = false

[directory]
format = "[$path]($style) [$read_only]($read_only_style)"
style = "bold blue"
truncate_to_repo = false
truncation_symbol = ""
truncation_length = 4
fish_style_pwd_dir_length = 1
read_only = " "
read_only_style = "red"
disabled = false

[git_branch]
format = "[\\($branch\\)]($style) "
style = "bold dimmed purple"
disabled = false

[git_status]
format = "([$ahead_behind]($style) )"
style = "none"
diverged = "⇡⇣"
disabled = false

[git_state]
disabled = false

[character]
format = "$symbol "
success_symbol = "[](dimmed cyan)"
error_symbol = "[](dimmed cyan)"
disabled = false

[cmd_duration]
min_time = 2
format = "[(\\($duration\\)\n\n)]($style)"
style = "bold red"
disabled = false

[time]
format = "[\\[$time\\]]($style) "
time_format = "%H:%M:%S"
style = "bold purple"
disabled = false
