#!/bin/zsh
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles


PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=20 color=0xCF1E140D corner_radius=12 margin=4 y_offset=4

# Not quite the same color as chalet white because the color rendering of the bar
# looks different than WezTerm/Neovim
custom_white=0xFFF7E6CF
chalet_light_brown=0xFFC69478
chalet_black=0xFF2E201E

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=0
  icon.font="UbuntuMono Nerd Font:Regular:15.0"
  label.font="UbuntuMono Nerd Font:Bold:15.0"
  icon.color=$chalet_black
  icon.background.color=$chalet_light_brown
  icon.background.height=16
  icon.background.corner_radius=8
  label.color=$custom_white
  icon.padding_left=8
  icon.padding_right=8
  label.padding_left=8
  label.padding_right=8
)
sketchybar --default "${default[@]}"

# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar \
  --add event aerospace_workspace_change \
  --add event mlx_update_list

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item front_app left \
           --set front_app icon="APP" script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched aerospace_workspace_change

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon="" script="$PLUGIN_DIR/clock.sh" \
\
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
\
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
\
           --add item cpu_percent right \
           --set cpu_percent update_freq=10 script="$PLUGIN_DIR/cpu.sh" \
\
           --add item memory_percent right \
           --set memory_percent update_freq=10 script="$PLUGIN_DIR/memory.sh"

sketchybar --add item mlx_servers e \
           --set mlx_servers update_freq=60 script="$PLUGIN_DIR/mlx_servers.sh" \
           --subscribe mlx_servers mlx_update_list

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
